### PR TITLE
Add a URI replacement handler

### PR DESCRIPTION
**Pull request by calebkiage**

### CODE REVIEW

**Review by baywet — COMMENTED** [review]
My initial suggestion was to move it to kiota http like the other languages. Mostly to save us from having to implement it another time for the dotnet SDK. Any objection to that instead?

**Comment by calebkiage** [comment]
Ok. How is the implementation for CSharp meant to work? Are there any constraints or would it be the same as this one?

**Comment by baywet** [comment]
It is meant to follow the typical middleware implementations with options and tracing. You can look at other languages including go to see how it was modeled.

**Comment by calebkiage** [comment]
So, the design for delegating replacement to a different type has to be changed?

**Comment by baywet** [comment]
Not by much I believe. It's mostly a matter of making the replacement keys and values configurable

**Pull request closed without merging**
